name: test check-gcd

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name: Permission Setting
        run: chmod +x test-manual-check-gcd.sh test-random-check-gcd.sh check-gcd.sh

      - name: Run test-manual-check-gcd
        run: ./test-check-gcd.sh

      - name: Run test-rondom-check-gcd
        run: ./test-random-check-gcd.sh
